//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otesevo.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_IT.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Site_Tagline {
            get {
                return ResourceManager.GetString("Site_Tagline", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Site_Footer_Desc {
            get {
                return ResourceManager.GetString("Site_Footer_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Site_Footer_Rights {
            get {
                return ResourceManager.GetString("Site_Footer_Rights", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Site_Footer_Location {
            get {
                return ResourceManager.GetString("Site_Footer_Location", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_News {
            get {
                return ResourceManager.GetString("Nav_News", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Book {
            get {
                return ResourceManager.GetString("Nav_Book", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Admin {
            get {
                return ResourceManager.GetString("Nav_Admin", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Reservations {
            get {
                return ResourceManager.GetString("Nav_Reservations", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_EditNews {
            get {
                return ResourceManager.GetString("Nav_EditNews", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_FileManager {
            get {
                return ResourceManager.GetString("Nav_FileManager", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_LogIn {
            get {
                return ResourceManager.GetString("Nav_LogIn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_LogOff {
            get {
                return ResourceManager.GetString("Nav_LogOff", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav_Register", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Meta_Title {
            get {
                return ResourceManager.GetString("Home_Meta_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Meta_Desc {
            get {
                return ResourceManager.GetString("Home_Meta_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Badge {
            get {
                return ResourceManager.GetString("Home_Hero_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Title_1 {
            get {
                return ResourceManager.GetString("Home_Hero_Title_1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Title_2 {
            get {
                return ResourceManager.GetString("Home_Hero_Title_2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Sub_1 {
            get {
                return ResourceManager.GetString("Home_Hero_Sub_1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Sub_2 {
            get {
                return ResourceManager.GetString("Home_Hero_Sub_2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Hero_Cta {
            get {
                return ResourceManager.GetString("Home_Hero_Cta", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_CheckIn {
            get {
                return ResourceManager.GetString("Home_CheckIn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_CheckOut {
            get {
                return ResourceManager.GetString("Home_CheckOut", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Guests {
            get {
                return ResourceManager.GetString("Home_Guests", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Guest_Singular {
            get {
                return ResourceManager.GetString("Home_Guest_Singular", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Guest_Plural {
            get {
                return ResourceManager.GetString("Home_Guest_Plural", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Home_Search {
            get {
                return ResourceManager.GetString("Home_Search", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Badge {
            get {
                return ResourceManager.GetString("About_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Hero_Title_1 {
            get {
                return ResourceManager.GetString("About_Hero_Title_1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Hero_Title_2 {
            get {
                return ResourceManager.GetString("About_Hero_Title_2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Meta_Title {
            get {
                return ResourceManager.GetString("About_Meta_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Meta_Desc {
            get {
                return ResourceManager.GetString("About_Meta_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_P1 {
            get {
                return ResourceManager.GetString("About_Story_P1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_P2 {
            get {
                return ResourceManager.GetString("About_Story_P2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_View_Prices {
            get {
                return ResourceManager.GetString("About_View_Prices", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_Badge {
            get {
                return ResourceManager.GetString("About_Story_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_Heading {
            get {
                return ResourceManager.GetString("About_Story_Heading", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_Full1 {
            get {
                return ResourceManager.GetString("About_Story_Full1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Story_Full2 {
            get {
                return ResourceManager.GetString("About_Story_Full2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Contact_Us {
            get {
                return ResourceManager.GetString("About_Contact_Us", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Offerings_Title {
            get {
                return ResourceManager.GetString("About_Offerings_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_Offerings_Sub {
            get {
                return ResourceManager.GetString("About_Offerings_Sub", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Nature_Title {
            get {
                return ResourceManager.GetString("Feature_Nature_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Nature_Desc {
            get {
                return ResourceManager.GetString("Feature_Nature_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Bungalows_Title {
            get {
                return ResourceManager.GetString("Feature_Bungalows_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Bungalows_Desc {
            get {
                return ResourceManager.GetString("Feature_Bungalows_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Health_Title {
            get {
                return ResourceManager.GetString("Feature_Health_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Health_Desc {
            get {
                return ResourceManager.GetString("Feature_Health_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Peace_Title {
            get {
                return ResourceManager.GetString("Feature_Peace_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Peace_Desc {
            get {
                return ResourceManager.GetString("Feature_Peace_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Beach_Title {
            get {
                return ResourceManager.GetString("Feature_Beach_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Beach_Desc {
            get {
                return ResourceManager.GetString("Feature_Beach_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Pitches_Title {
            get {
                return ResourceManager.GetString("Feature_Pitches_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Feature_Pitches_Desc {
            get {
                return ResourceManager.GetString("Feature_Pitches_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_CTA_Title {
            get {
                return ResourceManager.GetString("About_CTA_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string About_CTA_Sub {
            get {
                return ResourceManager.GetString("About_CTA_Sub", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Stats_Years {
            get {
                return ResourceManager.GetString("Stats_Years", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Stats_Bungalows {
            get {
                return ResourceManager.GetString("Stats_Bungalows", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Stats_Guests {
            get {
                return ResourceManager.GetString("Stats_Guests", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Badge {
            get {
                return ResourceManager.GetString("Gallery_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Title {
            get {
                return ResourceManager.GetString("Gallery_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide1_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide1_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide1_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide1_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide2_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide2_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide2_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide2_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide3_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide3_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide3_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide3_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide4_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide4_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide4_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide4_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide5_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide5_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide5_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide5_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide6_Title {
            get {
                return ResourceManager.GetString("Gallery_Slide6_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Gallery_Slide6_Desc {
            get {
                return ResourceManager.GetString("Gallery_Slide6_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Meta_Title {
            get {
                return ResourceManager.GetString("Contact_Meta_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Meta_Desc {
            get {
                return ResourceManager.GetString("Contact_Meta_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Badge {
            get {
                return ResourceManager.GetString("Contact_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Title_1 {
            get {
                return ResourceManager.GetString("Contact_Title_1", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Title_2 {
            get {
                return ResourceManager.GetString("Contact_Title_2", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Sub {
            get {
                return ResourceManager.GetString("Contact_Sub", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Address_Label {
            get {
                return ResourceManager.GetString("Contact_Address_Label", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Address_Val {
            get {
                return ResourceManager.GetString("Contact_Address_Val", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Email_Label {
            get {
                return ResourceManager.GetString("Contact_Email_Label", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Phone_Label {
            get {
                return ResourceManager.GetString("Contact_Phone_Label", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Contact_Social_Label {
            get {
                return ResourceManager.GetString("Contact_Social_Label", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Meta_Title {
            get {
                return ResourceManager.GetString("Res_Meta_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Meta_Desc {
            get {
                return ResourceManager.GetString("Res_Meta_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Badge {
            get {
                return ResourceManager.GetString("Res_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Title {
            get {
                return ResourceManager.GetString("Res_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Sub {
            get {
                return ResourceManager.GetString("Res_Sub", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Prices_Title {
            get {
                return ResourceManager.GetString("Res_Prices_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_FullName {
            get {
                return ResourceManager.GetString("Res_FullName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Email {
            get {
                return ResourceManager.GetString("Res_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Phone {
            get {
                return ResourceManager.GetString("Res_Phone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Guests {
            get {
                return ResourceManager.GetString("Res_Guests", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Accommodation {
            get {
                return ResourceManager.GetString("Res_Accommodation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_CheckIn {
            get {
                return ResourceManager.GetString("Res_CheckIn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_CheckOut {
            get {
                return ResourceManager.GetString("Res_CheckOut", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Info {
            get {
                return ResourceManager.GetString("Res_Info", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Submit {
            get {
                return ResourceManager.GetString("Res_Submit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Sending {
            get {
                return ResourceManager.GetString("Res_Sending", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Success_Title {
            get {
                return ResourceManager.GetString("Res_Success_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Success_Msg {
            get {
                return ResourceManager.GetString("Res_Success_Msg", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Required_Notice {
            get {
                return ResourceManager.GetString("Res_Required_Notice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Back_Home {
            get {
                return ResourceManager.GetString("Res_Back_Home", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Placeholder_Name {
            get {
                return ResourceManager.GetString("Res_Placeholder_Name", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Placeholder_Email {
            get {
                return ResourceManager.GetString("Res_Placeholder_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Placeholder_Phone {
            get {
                return ResourceManager.GetString("Res_Placeholder_Phone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Res_Placeholder_Info {
            get {
                return ResourceManager.GetString("Res_Placeholder_Info", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_Meta_Title {
            get {
                return ResourceManager.GetString("News_Meta_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_Meta_Desc {
            get {
                return ResourceManager.GetString("News_Meta_Desc", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_Badge {
            get {
                return ResourceManager.GetString("News_Badge", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_Title {
            get {
                return ResourceManager.GetString("News_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_Sub {
            get {
                return ResourceManager.GetString("News_Sub", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_ReadMore {
            get {
                return ResourceManager.GetString("News_ReadMore", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_NoItems {
            get {
                return ResourceManager.GetString("News_NoItems", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string News_PublishedOn {
            get {
                return ResourceManager.GetString("News_PublishedOn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Acc_Bungalow {
            get {
                return ResourceManager.GetString("Acc_Bungalow", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Acc_Trailer {
            get {
                return ResourceManager.GetString("Acc_Trailer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Acc_Pitch {
            get {
                return ResourceManager.GetString("Acc_Pitch", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Currency_MKD {
            get {
                return ResourceManager.GetString("Currency_MKD", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string PerNight {
            get {
                return ResourceManager.GetString("PerNight", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Val_Required {
            get {
                return ResourceManager.GetString("Val_Required", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Val_Email {
            get {
                return ResourceManager.GetString("Val_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Val_Generic_Error {
            get {
                return ResourceManager.GetString("Val_Generic_Error", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Js_Sending {
            get {
                return ResourceManager.GetString("Js_Sending", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Js_SendRequest {
            get {
                return ResourceManager.GetString("Js_SendRequest", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
    }
}
