// <auto-generated />
namespace Project_IT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class feedGallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feedGallery));
        
        string IMigrationMetadata.Id
        {
            get { return "202609121210157_feedGallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
